automation:
    ## Office Facebox Announcement
    - alias: "Office Facebox Announcement"
      initial_state: on
      trigger:
          - platform: state
            entity_id: binary_sensor.office_motion
            to: "on"
          - platform: state
            entity_id: binary_sensor.ra_cam_1_motion
            to: "on"
      action:
          - delay: 0:00:02
          - service: image_processing.scan
            entity_id: image_processing.officecam1
          - delay: 00:00:01
          - service: camera.snapshot
            data:
                entity_id: camera.office_cam1
                filename: !secret office_file_name
          - delay: 00:00:02
          - condition: and
            conditions:
                - condition: template
                  value_template: "{{ not is_state('sensor.office_camera_1_facebox_detection', 'unknown') }}"
                - condition: template
                  value_template: "{{ not is_state('sensor.office_camera_1_facebox_detection', 'none') }}"
          - delay: 00:00:02
          - service: notify.face_detection_activity_log
            data_template:
                title: Office Face Detection
                message: "{{ states('sensor.office_camera_1_facebox_detection') }} is in the Office"
                data:
                    photo:
                        url: !secret office_cam_url

    ## Basement Facebox Announcement
    - alias: "Basement Facebox Announcement"
      initial_state: on
      trigger:
          - platform: state
            entity_id: binary_sensor.basement_motion
            to: "on"
      action:
          - delay: 00:00:02
          - service: image_processing.scan
            entity_id: image_processing.kimmy_camera_1
          - delay: 00:00:01
          - service: camera.snapshot
            data:
                entity_id: camera.kimmycamera1
                filename: !secret basement_file_name
          - delay: 00:00:02
          - condition: and
            conditions:
                - condition: template
                  value_template: "{{ not is_state('sensor.kimmy_camera_1_facebox_detection', 'unknown') }}"
                - condition: template
                  value_template: "{{ not is_state('sensor.kimmy_camera_1_facebox_detection', 'none') }}"
          - service: notify.face_detection_activity_log
            data_template:
                title: Basement Face Detection
                message: "{{ states('sensor.kimmy_camera_1_facebox_detection') }} is in the Basement"
                data:
                    photo:
                        url: !secret basement_cam_url

    ## Kitchen Facebox Announcement
    - alias: "Kitchen Facebox Announcement"
      initial_state: on
      trigger:
          - platform: state
            entity_id: binary_sensor.kitchen_motion
            to: "on"
      action:
          - delay: 00:00:02
          - service: image_processing.scan
            entity_id: image_processing.kitchencam2
          - service: image_processing.scan
            entity_id: image_processing.cat_area_camera_3
          - service: image_processing.scan
            entity_id: image_processing.living_room_camera_4
          - delay: 00:00:01
          - service: camera.snapshot
            data:
                entity_id: camera.kitchen_cam2
                filename: !secret kitchen_file_name
          - service: camera.snapshot
            data:
                entity_id: camera.cat_area_cam3
                filename: !secret cat_area_file_name
          - service: camera.snapshot
            data:
                entity_id: camera.living_room_cam4
                filename: !secret livingroom_file_name
          - delay: 00:00:02
          - condition: or
            conditions:
                - condition: and
                  conditions:
                      - condition: template
                        value_template: "{{ not is_state('sensor.kitchen_camera_2_facebox_detection', 'unknown') }}"
                      - condition: template
                        value_template: "{{ not is_state('sensor.kitchen_camera_2_facebox_detection', 'none') }}"
                - condition: and
                  conditions:
                      - condition: template
                        value_template: "{{ not is_state('sensor.cat_area_camera_3_facebox_detection', 'unknown') }}"
                      - condition: template
                        value_template: "{{ not is_state('sensor.cat_area_camera_3_facebox_detection', 'none') }}"
          - service: notify.face_detection_activity_log
            data_template:
                title: Kitchen Face Detection
                message: "{{ states('sensor.kitchen_camera_2_facebox_detection') }} is in the Kitchen"
                data:
                    photo:
                        url: !secret kitchen_cam_url
