# Main Configuration
homeassistant:
    name: IronYNet
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long
    elevation: 161
    unit_system: metric
    time_zone: America/Toronto
    packages: !include_dir_named packages
    whitelist_external_dirs:
        - /config/logs/
    auth_providers:
        - type: homeassistant
        - type: legacy_api_password
          api_password: !secret http_password
        - type: trusted_networks
          trusted_networks:
              - 127.0.0.1
              - ::1
              - fd00::/8
              - 192.168.1.0/24

# Web Socket API
websocket_api:

# HTTP
http:
    base_url: !secret base_url
    use_x_forwarded_for: True
    trusted_proxies:
        - 127.0.0.1
        - 192.168.1.5
        - 192.168.1.6
        - 192.168.1.1
        - ::1
        - fd00::/8
    #ip_ban_enabled: True
    #login_attempts_threshold: 5

# Front End
frontend:
    themes: !include_dir_merge_named themes/
    javascript_version: latest

logger:
    default: critical
    logs:
        aiohttp: fatal
        homeassistant.core: fatal
        homeassistant.components.http.ban: fatal
        homeassistant.components.http: fatal
######### CUSTOM COMPONENTS #############
# Home Assistant Community Store
hacs:
    token: !secret github
# Breaking Changes
breaking_changes:
# SpotCast
#spotcast:
#  username: !secret spotify_primary_username
#  password: !secret spotify_primary_password
#  accounts:
#    dave:
#      username: !secret spotify_dave_username
#      password: !secret spotify_kayla_password
#    kayla:
#      username: !secret spotify_dave_username
#      password: !secret spotify_kayla_password

